apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ngrok-hello-ingress
spec:
  ingressClassName: ngrok
  rules:
    - host: "dog-ideal-externally.ngrok-free.app"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: heybot-service
                port:
                  number: 7861